AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  FunctionName:
    Type: String
  FunctionAlias:
    Type: String
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref "FunctionName"
      DeploymentPreference:
        Type: AllAtOnce
      AutoPublishAlias: !Ref "FunctionAlias"
      Handler: function.handler
      Tracing: Active
      Runtime: provided
      CodeUri: ./handler.zip
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Effect: Allow
              Action:
                - acm:DescribeCertificate
                - acm:RequestCertificate
                - acm:DeleteCertificate
                - route53:ListHostedZones
                - route53:ChangeResourceRecordSets
              Resource: "*"
Outputs:
  FunctionArn:
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"